- name: Create Minecraft-Group
  ansible.builtin.group:
    name: "{{ minecraft_group }}"
  become: true

- name: Create Minecraft-User
  ansible.builtin.user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  become: true

- name: Create Directory for Server
  ansible.builtin.file:
    path: "{{ minecraft_home }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  become: true

- name: Download Server
  ansible.builtin.get_url:
    url: https://papermc.io/api/v2/projects/paper/versions/{{ minecraft_version }}/builds/{{ minecraft_build }}/downloads/paper-{{ minecraft_version }}-{{ minecraft_build }}.jar
    dest: "{{ minecraft_home }}/minecraft.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  become: true
